// Box states
module.exports = {
  BOX_EMPTY_DOOR_CLOSED: 1,
  INTRODUCING_SCOOTER_BOX_EMPTY_DOOR_OPEN_LOADER_UNPLUGGED: 2,
  INTRODUCING_SCOOTER_BOX_EMPTY_DOOR_OPEN_LOADER_PLUGGED: 3,
  BOX_OCCUPIED_DOOR_CLOSED: 4,
  REMOVING_SCOOTER_BOX_OCCUPIED_DOOR_OPEN_LOADER_PLUGGED: 5,
  REMOVING_SCOOTER_BOX_OCCUPIED_DOOR_OPEN_LOADER_UNPLUGGED: 6
}
