// Box states
module.exports = {
  // BOX_EMPTY_DOOR_CLOSED: 1,
  // INTRODUCING_SCOOTER_BOX_EMPTY_DOOR_OPEN_LOADER_UNPLUGGED: 2,
  // INTRODUCING_SCOOTER_BOX_EMPTY_DOOR_OPEN_LOADER_PLUGGED: 3,
  // BOX_OCCUPIED_DOOR_CLOSED: 4,
  // REMOVING_SCOOTER_BOX_OCCUPIED_DOOR_OPEN_LOADER_PLUGGED: 5,
  // REMOVING_SCOOTER_BOX_OCCUPIED_DOOR_OPEN_LOADER_UNPLUGGED: 6
  NEITHER_PARKING_NOT_RENTING: 0,

  PARKING_MODE_INTRODUCING_SCOOTER_ORDER_TO_OPEN_DOOR_SENT: 11, //Before this the state was NEITHER_PARKING_NOT_RENTING
  PARKING_MODE_INTRODUCING_SCOOTER_DOOR_OPEN_CONFIRMATION_RECEIVED: 12,
  PARKING_MODE_INTRODUCING_SCOOTER_DOOR_CLOSED_CONFIRMATION_RECEIVED: 13,
  PARKING_MODE_PULLING_OUT_SCOOTER_ORDER_TO_OPEN_DOOR_SENT: 14,
  PARKING_MODE_PULLING_OUT_SCOOTER_DOOR_OPEN_CONFIRMATION_RECEIVED: 15,
  PARKING_MODE_PULLING_OUT_SCOOTER_DOOR_CLOSED_CONFIRMATION_RECEIVED: 16, //After user confirmation the state goes to NEITHER_PARKING_NOT_RENTING.

  RENTING_MODE_PULLING_OUT_SCOOTER_ORDER_TO_OPEN_DOOR_SENT: 21, //Before this the state was NEITHER_PARKING_NOT_RENTING
  RENTING_MODE_PULLING_OUT_SCOOTER_DOOR_OPEN_CONFIRMATION_RECEIVED: 22,
  RENTING_MODE_PULLING_OUT_SCOOTER_CHARGER_PULLED_OUT_CONFIRMATION_RECEIVED: 23,
  RENTING_MODE_PULLING_OUT_SCOOTER_DOOR_CLOSED_CONFIRMATION_RECEIVED: 24,
  RENTING_MODE_INTRODUCING_SCOOTER_ORDER_TO_OPEN_DOOR_SENT: 25,
  RENTING_MODE_INTRODUCING_SCOOTER_DOOR_OPEN_CONFIRMATION_RECEIVED: 26,
  RENTING_MODE_INTRODUCING_SCOOTER_CHARGER_PLUGGED_IN_CONFIRMATION_RECEIVED: 27,
  RENTING_MODE_INTRODUCING_SCOOTER_DOOR_CLOSED_CONFIRMATION_RECEIVED: 28, //After user confirmation the state goes to NEITHER_PARKING_NOT_RENTING.
}
